apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
  labels:
    app: event-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-system
      service: event
  template:
    metadata:
      labels:
        app: event-system
        service: event
    spec:
      containers:
        - name: event-deployment
          image: websoa-event-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: event
