version: '3.8'

services:
  active-mq:
    build: ./active-mq/
    ports:
      - "8161:8161"
      - "61616:61616"

  distribution-service:
    build:
      dockerfile: ./distribution-service/Dockerfile
      context: ./
    ports:
      - "8080"

  event-service:
    build:
      dockerfile: ./event-service/Dockerfile
      context: ./
    ports:
      - "8080"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  payment-service:
    build:
      dockerfile: ./payment-service/Dockerfile
      context: ./
    ports:
      - "8080"
    depends_on:
      - active-mq

  ticket-service:
    build:
      dockerfile: ./ticket-service/Dockerfile
      context: ./
    ports:
      - "8080"

  user-service:
    build:
      dockerfile: ./user-service/Dockerfile
      context: ./
    ports:
      - "8080"

  validation-service:
    build:
      dockerfile: ./validation-service/Dockerfile
      context: ./
    ports:
      - "8080"
    depends_on:
      - ticket-service
