apiVersion: apps/v1
kind: Deployment
metadata:
  name: active-mq-deployment
  labels:
    app: event-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-system
      service: active-mq
  template:
    metadata:
      labels:
        app: event-system
        service: active-mq
    spec:
      containers:
        - name: active-mq-deployment
          image: websoa-active-mq
          imagePullPolicy: Never
          ports:
            - containerPort: 8161
            - containerPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: active-mq
spec:
  type: LoadBalancer
  ports:
    - port: 61616
      targetPort: 61616
#    - port: 80
#      targetPort: 8161
  selector:
    service: active-mq
