//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.23 at 07:17:33 PM CET 
//

@XmlSchema(namespace = "http://websoa.utwente.nl/api/payment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package websoa.payment.daos;

import javax.xml.bind.annotation.XmlSchema;
